name = "42"
projects = [
	"libft",
	"ft_printf",
	"get_next_line",
	"pipex",
	"push_swap",
	"so_long",
	"philosophers/philo",
	"minishell",
	"cpp00/ex00",
	"cpp00/ex01",
	"cpp01/ex00",
	"cpp01/ex01",
	"cpp01/ex02",
	"cpp01/ex03",
	"cpp01/ex04",
	"cpp01/ex05",
]

[scripts]
