name = "42"
projects = [
	"libft",
	"ft_printf",
	"get_next_line",
	"pipex",
	"push_swap",
	"so_long",
	"philosophers/philo",
	"minishell",
	"cpp00/ex00",
	"cpp00/ex01",
	"cpp01/ex00",
	"cpp01/ex01",
	"cpp01/ex02",
	"cpp01/ex03",
	"cpp01/ex04",
	"cpp01/ex05",
	"cpp02/ex00",
	"cpp02/ex01",
	"cpp02/ex02",
	"cpp03/ex00",
	"cpp03/ex01",
	"cpp03/ex02",
	"cpp04/ex00",
	"cpp04/ex01",
	"cpp04/ex02",
	"cpp04/ex03",
	"cpp05/ex00",
	"cpp05/ex01",
	"cpp05/ex02",
	"cpp05/ex03",
	"cpp06/ex00",
	"cpp06/ex01",
	"cpp06/ex02",
	"cpp07/ex00",
	"cpp07/ex01",
	"cpp07/ex02",
	"cpp08/ex00",
	"cpp08/ex01",
	"cpp08/ex02",
	"cpp09/ex00",
	"cpp09/ex01",
	"cpp09/ex02",
]

[scripts]
