name = "ft_irc"

[scripts]
build = { cmd = "make" }
clean = { cmd = "make fclean" }
lint = { cmd = "cppcheck --suppress=missingIncludeSystem --suppress=constParameterPointer --inline-suppr --enable=all ." }
