services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
    ports:
      - 8787:8787
    restart: unless-stopped
  www:
    build:
      context: apps/www
      dockerfile: Dockerfile
    volumes:
      - ./apps/www:/app
      - /app/node_modules
    ports:
      - 5173:5173
    env_file:
      - apps/www/.env
    restart: unless-stopped

networks:
  net:
    driver: bridge
