services:
  # postgres:
  #   image: postgres:16
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   # volumes:
  #   #   - data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  www:
    build:
      context: apps/www
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    env_file:
      - apps/www/.env
    restart: unless-stopped
    volumes:
      - ./apps/www:/app

networks:
  net:
    driver: bridge
