services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - pgdata:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: apps/api
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped
  #   networks:
  #     - net

  # nginx:
  #   env_file: .env
  #   container_name: nginx
  #   build:
  #     context: ./apps/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5173:443
  #     - 8080:443
  #   restart: on-failure
  #   networks:
  #     - net
  #   depends_on:
  #     - www
    #   - logstash

  www:
    build:
      context: apps/www
      dockerfile: Dockerfile
    volumes:
      - ./apps/www:/app
      - /app/node_modules
    ports:
      - 5173:5173
    # expose:
      # - 5173
    env_file:
      - apps/www/.env
    restart: unless-stopped
    networks:
      - net

  djangoapp:
    container_name: djangoapp
    build:
      context: apps/djangoproject
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - apps/djangoproject/.env
    depends_on:
      - postgres
    networks:
      - net
volumes:
  pgdata: {}

networks:
  net:
    driver: bridge
