version: "3.9"

services:
  # db:
  #   container_name: mariadb
  #   restart: unless-stopped
  #   build: ./requirements/mariadb
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   env_file:
  #     - .env
  #   networks:
  #     - net
  nginx:
    container_name: nginx
    restart: unless-stopped
    build: ./requirements/nginx
    ports:
      - "80:80"
      # - "9000:80"
      # - "9000:443"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  db_data:
  wp_data:
