version: "3.9"

services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - net
  #   healthcheck:
  #     test:
  #       [
  #         'CMD',
  #         'mysqladmin',
  #         'ping',
  #         '-u',
  #         'root',
  #         '-p${MYSQL_ROOT_PASSWORD}'
  #       ]
  #     interval: 1m
  #     timeout: 10s
  #     retries: 5
  nginx:
    container_name: nginx
    restart: unless-stopped
    build: requirements/nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      # - wp_data:/var/www/html
      - ./web:/var/www/html
      # env_file:
      #   - .env
    networks:
      - net
  wordpress:
    container_name: wordpress
    restart: unless-stopped
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      # - wp_data:/var/www/html
      - ./web:/var/www/html
    env_file:
      - .env
    networks:
      - net
      # healthcheck:
      #   test: [ 'CMD', 'curl', '--fail', 'http://localhost:9000' ]
      #   interval: 1m
      #   timeout: 10s
      #   retries: 5

networks:
  net:
    driver: bridge

volumes:
  db_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/hvine/data/db
    #   o: bind
  wp_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/hvine/data/wp
    #   o: bind
