services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build: requirements/mariadb
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/mysql  --execute \"SHOW DATABASES;\"" ]
      interval: 15s
      retries: 10
      start_period: 20s
    volumes:
      - /home/hvine/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - net
  nginx:
    container_name: nginx
    restart: unless-stopped
    build: requirements/nginx
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - /home/hvine/data/wordpress:/var/www/html
    networks:
      - net
  wordpress:
    container_name: wordpress
    restart: unless-stopped
    build: requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - /home/hvine/data/wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - net

networks:
  net:
    driver: bridge
