# Generated by Django 3.2.5 on 2024-09-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('displayName', models.CharField(max_length=250)),
                ('fortyTwoId', models.IntegerField(unique=True)),
                ('otpEnabled', models.BooleanField(default=False)),
                ('otpVerified', models.BooleanField(default=False)),
                ('otpSecret', models.CharField(max_length=250, null=True)),
                ('otpAuthUrl', models.CharField(max_length=250, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tournaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('loserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loserId', to='djangoapp.users')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to='djangoapp.users')),
                ('winnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnerId', to='djangoapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.CharField(max_length=250)),
                ('opponent', models.CharField(max_length=250)),
                ('playerScore', models.IntegerField()),
                ('opponentScore', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('tournamentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.tournaments')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.users')),
            ],
        ),
    ]
