# Generated by Django 3.2.5 on 2024-09-22 18:49

from django.db import migrations, models
import djangoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default=djangoapp.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
