# Generated by Django 3.2.5 on 2024-09-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('djangoapp', '0002_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='loserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loserId', to='users.users'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='winnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnerId', to='users.users'),
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
