name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Lint
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install norminette
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: norminette -R CheckForbiddenSourceHeader $(find . -name "*.c" -o -name "*.h")
