name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install norminette
      - name: Lint
        run: norminette -R CheckForbiddenSourceHeader $(find . -name "*.c" -o -name "*.h")
  build:
    name: Build
    # needs: lint
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: \! find . -name Makefile -type f -execdir make re \; 2>&1 | grep -qF 'Error 1'
